title: Sveleven
styles:
  - https://cdn.jsdelivr.net/npm/prismjs@1/themes/prism-tomorrow.min.css
  - https://cdn.jsdelivr.net/npm/prismjs@1/plugins/treeview/prism-treeview.min.css
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@7/css/all.min.css
  - /styles.css
scripts:
  - https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-core.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1/plugins/autoloader/prism-autoloader.min.js
  - https://cdn.jsdelivr.net/npm/prismjs@1/plugins/treeview/prism-treeview.min.js
footer: |-
  Made with <i class="fa-solid fa-heart fa-sm"></i>＋<i class="fa-solid fa-mug-hot align-text-top"></i>
  by <a href="https://any.digital/" target="_blank"><em>Any</em>digital</a> © 2025–{{ year }}
gtm_id: YOUR_GTM_ID
