title: Sveleven
dependencies:
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@7/css/all.min.css
  - https://cdn.jsdelivr.net/npm/@anydigital/bricks@^1.0.0-alpha/dist/bricks.min.css
  - /styles.css
